# -*- coding: utf-8 -*-
"""Part6_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUc8RtAbkGq1igr21fQEHhHrxgM91OXy

# End-to-End Automated Simulation & Inference Pipeline for Wildfire Detection, Geoparsing and Mapping

**Description:**

This script acts as the "Master" inference pipeline for the fully automated - just by clicking "Run" - detection, geoparsing and mapping of fires based on X (Twitter) posts in Greece.


It seamlessly integrates the standalone modules developed in earlier stages (Text Cleaning, Geoparsing & Mapping) into a single, fully automated workflow designed to process new, unlabeled datasets. It utilizes Cloud architecture based on Hugging Face (for the trained models) and GitHub (for the scripts and datasets).


**Pipeline Stages & Methodology:**

1.  **Automated Text Cleaning:**
* Dynamically imports and utilizes the `part2_text_cleaning.py` module.
* Processes raw tweets into a specific cleaned format (Light, Advanced, or Hard Cleaning) which is selected based on the application.

2.  **Model Inference:**
* The Binary Classification and Multilabel Classification scripts trained and evaluated numerous models. The fine-tuned ones were archived in a Hugging Face Repository and they are accessed through it.
* A customizable decision threshold (e.g., 0.30) is applied to extract the final `Predicted Label`.

3.  **Geoparsing & Interactive Mapping:**
* Imports the `part5_geoparsing_and_mapping.py` module to handle the spatial analysis.
* Filters the dataset for predicted fire events and their fire types, extracts locations via Named Entity Recognition (NER), disambiguates toponyms, and applies DBSCAN clustering.
* Exports the final operational data into a CSV and generates a Folium map.

**References:**

*GreekBERT: https://github.com/nlpaueb/greek-bert*

*Hugging Face Transformers: https://huggingface.co/docs/transformers/*

*Nominatim API (OSM): https://nominatim.org/release-docs/develop/api/Search/*
"""

# ==========================================
# CELL 1: Libraries Setup & Installations
# ==========================================
!pip install emoji -q
!pip install spacy -q
!python -m spacy download el_core_news_lg -q
!pip install gr-nlp-toolkit geopy folium scikit-learn -q

import pandas as pd
import io
import os
import numpy as np
import torch
import sys
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer
from datasets import Dataset

print("\nAll libraries installed successfully!")

# Commented out IPython magic to ensure Python compatibility.
# ==========================================
# CELL 2a: Definition of Scripts Path (Github)
# ==========================================

REPO_URL = "https://github.com/mariossmrs/greek-wildfire-detection-pipeline.git"
REPO_NAME = "greek-wildfire-detection-pipeline"

if not os.path.exists(REPO_NAME):
    !git clone {REPO_URL}
else:
#     %cd {REPO_NAME}
    !git pull
#     %cd ..

sys.path.append(os.path.abspath(REPO_NAME))

from part2_text_cleaning import run_text_cleaning
from part5_geoparsing_and_mapping import run_mapping

print("[SUCCESS] Scripts Loaded!")

# Simulation dataset (e.g. Varnavas Fire)
DATA_PATH = f"/content/{REPO_NAME}/data/varnavas_fire.csv"

raw_df = pd.read_csv(DATA_PATH)
print(f"[SUCCESS] Loaded {len(raw_df)} tweets from the simulation dataset.")

# ==========================================
# CELL 2b: Definition of Models Path (Hugging Face)
# ==========================================

MODEL_PATH = "mariossmrs/greek-bert-fire-detection-binary-classification"
MULTILABEL_MODEL_PATH = "mariossmrs/greek-xlm-roberta-fire-type-multilabel-classification"

print("[SUCCESS] Model directories found!")

# ==========================================
# CELL 3: Text Cleaning
# ==========================================

print("--- STEP 2: Text Cleaning ---")

# Execute the text cleaning pipeline
cleaned_df = run_text_cleaning(raw_df)

# Export the cleaned dataset for safekeeping
export_filename = "simulation_cleaned_tweets.csv"
cleaned_df.to_csv(export_filename, index=False)
print(f"\n[SUCCESS] Cleaned dataset saved in Colab as '{export_filename}'.")

# ====================================================================================
# CELL 4a: Model Inference (GreekBERT) - Binary Classification
# ====================================================================================

print("--- STEP 3: Model Inference ---")

def run_inference(df, model_path, threshold=0.30):
    """
    Performs inference using the fine-tuned model stored in Hugging Face.
    Includes custom thresholding and logs fire probabilities.

    About the threshold (0.30):
    In emergency response contexts, minimizing False Negatives (missed events)
    is far more critical than minimizing False Positives (false alarms).
    By lowering the decision threshold from the default 0.50 to 0.30, we intentionally
    prioritize Recall over Precision. This ensures that posts with even a moderate
    probability of reporting an active fire are flagged for downstream spatial processing.
    """
    print(f"\nLoading trained GreekBERT from Hugging Face: {model_path}...")

    # 1. Load Tokenizer and Model from the Drive path
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_path)

    # 2. Prepare data (GreekBERT requires 'Advanced Cleaned Text')
    texts = df['Advanced Cleaned Text'].tolist()

    def tokenize_function(examples):
        return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=128)

    dataset = Dataset.from_dict({'text': texts})
    dataset = dataset.map(tokenize_function, batched=True)

    # 3. Execution
    print("Executing predictions...")
    trainer = Trainer(model=model)
    raw_predictions, _, _ = trainer.predict(dataset)

    # Convert logits to probabilities
    logits_tensor = torch.tensor(raw_predictions)
    probabilities = torch.softmax(logits_tensor, dim=-1).numpy()
    fire_probs = probabilities[:, 1] # Probability for Class 1 (Fire)

    # Apply custom threshold
    predictions = (fire_probs >= threshold).astype(int)

    # Log results back to DataFrame
    df['Fire Probability'] = np.round(fire_probs, 3)
    df['Predicted Label'] = predictions

    fires_found = sum(predictions == 1)
    print(f"\nInference complete!\nTotal Dataset: {len(predictions)} Tweets\nPredicted as Fire-Related:{fires_found} Tweets")

    return df

# ====================================================================================
# CELL 4b: Model Inference (RoBERTa) - Multilabel Classification
# ====================================================================================

def run_multilabel_inference(df, model_path, threshold_forest=0.5, threshold_urban=0.5):
    """
    Performs multilabel inference ONLY on tweets predicted as fire-related.
    """
    print(f"\n--- Loading Multilabel Model from Hugging Face: {model_path} ---")

    # 1. Filter dataset: Keep only tweets predicted as fire
    df_fire = df[df['Predicted Label'] == 1].copy()

    if df_fire.empty:
        print("[INFO] No fire-related tweets found to classify further.")
        # Default initialization if nothing found
        df['is_wildland_pred'] = 0
        df['is_urban_pred'] = 0
        return df

    # 2. Load Tokenizer and Model
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_path)

    # 3. Prepare data (use the same text column you trained the multilabel model on)
    texts = df_fire['Light Cleaned Text'].astype(str).tolist() # Assuming XLM-RoBERTa won - change to 'Advanced Cleaned' if GreekBERT won

    def tokenize_function(examples):
        return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=128)

    dataset = Dataset.from_dict({'text': texts})
    dataset = dataset.map(tokenize_function, batched=True)

    # 4. Predict
    print("Executing Multilabel predictions...")
    trainer = Trainer(model=model)
    raw_predictions, _, _ = trainer.predict(dataset)

    # Convert logits to probabilities (Sigmoid)
    probabilities = torch.sigmoid(torch.tensor(raw_predictions)).numpy()

    # Apply thresholds independently
    is_wildland_pred = (probabilities[:, 0] > threshold_forest).astype(int)
    is_urban_pred = (probabilities[:, 1] > threshold_urban).astype(int)

    # 5. Merge results back to the original DataFrame
    # 5. Merge results back to the original DataFrame
    # Create columns initialized to 0
    df['is_wildland_pred'] = 0
    df['is_urban_pred'] = 0

    # Update the rows that were predicted as fire
    df.loc[df['Predicted Label'] == 1, 'is_wildland_pred'] = is_wildland_pred
    df.loc[df['Predicted Label'] == 1, 'is_urban_pred'] = is_urban_pred

    df_results = df[df['Predicted Label'] == 1]
    total_fires = len(df_results)

    forest_only = len(df_results[(df_results['is_wildland_pred'] == 1) & (df_results['is_urban_pred'] == 0)])
    urban_only = len(df_results[(df_results['is_wildland_pred'] == 0) & (df_results['is_urban_pred'] == 1)])
    mixed_fire = len(df_results[(df_results['is_wildland_pred'] == 1) & (df_results['is_urban_pred'] == 1)])
    unidentified = len(df_results[(df_results['is_wildland_pred'] == 0) & (df_results['is_urban_pred'] == 0)])

    print("\nMultilabel inference complete!\n")
    print(f"Total Fire-Related Tweets Analyzed: {total_fires}")
    print("--------------------------------------------------")
    print(f"Forest Fires:                       {forest_only}")
    print(f"Urban Fires:                        {urban_only}")
    print(f"Mixed Fires (Wildland-Urban):       {mixed_fire}")
    print(f"Unidentified Fire Type:             {unidentified}")
    print("--------------------------------------------------")

    return df

# ==========================================
# CELL 5: Run Inference & Save prediction file
# ==========================================

# 1. Binary Inference
predicted_df = run_inference(cleaned_df, model_path=MODEL_PATH, threshold=0.30)

# 2. Multilabel Inference
final_predicted_df = run_multilabel_inference(predicted_df, model_path=MULTILABEL_MODEL_PATH)

# Save results locally
final_predicted_df.to_csv("simulation_predicted_tweets.csv", index=False)
print("\n[SUCCESS] Results saved as 'simulation_predicted_tweets.csv'.")

# ==========================================
# CELL 6: Geoparsing & Mapping
# ==========================================

print("\n--- STEP 4: Geoparsing & Mapping ---")

# Generate the map using the predictions
mapped_df = run_mapping(final_predicted_df)

# Download the final map
if mapped_df is not None:
    print("\n[SUCCESS] Fire map generated successfully!")
    print("\nFiles ('fire_events_map.html' & 'fire_events_geoparsed.csv') saved locally in Colab (left panel 'Files').")