# -*- coding: utf-8 -*-
"""Part1_X_Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2YxQsk2y_eYbA63miZ2ThvPN159Mxgp

# X Scraping Script for Greek Fire-Related Posts Extraction
**Description:**

This script leverages the 'twikit' python library to scrape posts from X (formerly known as Twitter) related to fire events in Greece.

It is designed to build a dataset of X posts that will be then manually labeled (Fire Related Posts vs Non-Fire Related Posts) and eventually processed through a Machine Learning pipeline for key event information extraction.

**Methodology:**

Scraping based on Keywords: Use of Greek fire-related terms and Greeklish hashtags to strictly minimize contextual noise.

*   *Keyword selection:* πυρκαγιά, φωτιά, πυροσβεστική, καίγεται, φωτιαα, αναζωπύρωση, εκκένωση

*   *Hashtag selection:* #fwtia, #fotia, #pyrkagia, #pirkagia, #pyrosvestiki, #pirosvestiki

*Note that by searching "φωτιά", X will automatically retrieve "φωτια", "ΦΩΤΙΑ", etc.*

**References:**

*Twikit library: https://github.com/d60/twikit*

*Monkey patch: https://github.com/d60/twikit/issues/408*

*Pull request: https://github.com/d60/twikit/pull/418*

*The 'twikit' library currently requires a monkey patch due to a recent change in X's architecture. This addition will be removed when the updated library has been released.*
"""

# LIBRARIES
#!pip install twikit

# Github pull request due to X API error (to be deleted with the new update)
!pip uninstall twikit -y
!pip install git+https://github.com/d60/twikit.git@refs/pull/418/head

import asyncio
import csv
import time
import random
import re
import os
import datetime

from twikit.errors import NotFound, TooManyRequests
from twikit import Client
from google.colab import userdata

# MONKEY PATCH - Temporary Library Fix
import re as _re
_tx_mod = __import__('twikit.x_client_transaction.transaction', fromlist=['ClientTransaction'])
_tx_mod.ON_DEMAND_FILE_REGEX = _re.compile(
    r""",(\d+):["']ondemand\.s["']""", flags=(_re.VERBOSE | _re.MULTILINE))
_tx_mod.ON_DEMAND_HASH_PATTERN = r',{}:"([0-9a-f]+)"'

async def _patched_get_indices(self, home_page_response, session, headers):
    key_byte_indices = []
    response = self.validate_response(home_page_response) or self.home_page_response
    on_demand_file_index = _tx_mod.ON_DEMAND_FILE_REGEX.search(str(response)).group(1)
    regex = _re.compile(_tx_mod.ON_DEMAND_HASH_PATTERN.format(on_demand_file_index))
    filename = regex.search(str(response)).group(1)
    on_demand_file_url = f"https://abs.twimg.com/responsive-web/client-web/ondemand.s.{filename}a.js"
    on_demand_file_response = await session.request(method="GET", url=on_demand_file_url, headers=headers)
    key_byte_indices_match = _tx_mod.INDICES_REGEX.finditer(str(on_demand_file_response.text))
    for item in key_byte_indices_match:
        key_byte_indices.append(item.group(2))
    if not key_byte_indices:
        raise Exception("Couldn't get KEY_BYTE indices")
    key_byte_indices = list(map(int, key_byte_indices))
    return key_byte_indices[0], key_byte_indices[1:]

_tx_mod.ClientTransaction.get_indices = _patched_get_indices
# END OF MONKEY PATCH

# Secure Loading of X Credentials based on Colab Secrets
# Cookies used derived from a Throwaway Account
try:
    AUTH_TOKEN = userdata.get('X_AUTH_TOKEN')
    CT0 = userdata.get('X_CT0')
    print("Cookies loaded successfully from Colab Secrets!")
except Exception as e:
    raise ValueError(
        "\n[ERROR]: X Cookies missing.\n"
    )

OUTPUT_FILE  = 'fire_dataset.csv'

# Keyword Selection (Greek & Greeklish)
KEYWORDS = "((πυρκαγιά OR φωτιά OR πυροσβεστική OR καίγεται OR φωτιαα OR αναζωπύρωση OR εκκένωση) lang:el) OR (#fwtia OR #fotia OR #pyrkagia OR #pirkagia OR #pyrosvestiki OR #pirosvestiki)"

# Scraping Periods: (since, until, tweet_limit, description)
# since/until format: YYYY-MM-DD
PERIODS = [
    ('2024-07-02', '2024-07-04', 500, 'Period 1'), # 500 tweets
    ('2025-07-01', '2025-07-03', 500, 'Period 2'),
    ('2025-07-22', '2025-07-24', 500, 'Period 3'),
    ('2025-08-11', '2025-08-13', 1000, 'Period 4'), # 1000 tweets - Patras fire
    ('2025-08-27', '2025-08-29', 500, 'Period 5')
]

# SCRAPING FUNCTION
# Executes the search query using "Time-Travel" pagination to bypass X's looping bug
async def scrape_period(client, since, until, limit, description, writer, file):
    # Build the static part of the query
    base_query = f"({KEYWORDS}) since:{since}"

    # The dynamic variable that will change in each loop
    current_until = f"until:{until}"

    print(f"\n Period: {description} ({since} → {until}) | Target: {limit} tweets")

    tweet_count = 0
    seen_tweet_ids = set() # Memory set to strictly avoid duplicate IDs

    while tweet_count < limit:
        # Build the query for this specific loop
        query = f"{base_query} {current_until}"

        try:
            # ALWAYS execute a "fresh" search, NEVER use tweets.next()
            tweets = await client.search_tweet(query, product='Latest', count=20)

            if not tweets:
                print(f"  No more tweets found. Stopped at {tweet_count}.")
                break

            oldest_timestamp = None
            new_tweets_in_batch = 0

            for tweet in tweets:
                if tweet_count >= limit:
                    break

                # Skip if we have already scraped this exact tweet in a previous batch
                if tweet.id in seen_tweet_ids:
                    continue

                seen_tweet_ids.add(tweet.id)
                new_tweets_in_batch += 1

                # ---------------------------------------------------------
                # TIME CONVERSION: Find the Unix Timestamp of the tweet
                # ---------------------------------------------------------
                try:
                    # twikit returns the date format: 'Tue Jul 02 10:11:12 +0000 2024'
                    dt = datetime.datetime.strptime(tweet.created_at, '%a %b %d %H:%M:%S %z %Y')
                    tweet_unix = int(dt.timestamp())

                    # Keep the timestamp of the OLDEST tweet in the current batch
                    if oldest_timestamp is None or tweet_unix < oldest_timestamp:
                        oldest_timestamp = tweet_unix
                except Exception as e:
                    print(f"  Date parsing error: {e}")

                writer.writerow([
                    tweet.created_at,
                    tweet.id,
                    tweet.text.replace('\n', ' ').replace('\r', ' '),
                    tweet.favorite_count,
                    tweet.retweet_count,
                    '',
                    '',
                    ''
                ])
                tweet_count += 1

            # Safety net: Break if X loops and returns only old data
            if new_tweets_in_batch == 0:
                print(f"  Twitter returned no new data (possible date limit reached).")
                break

            # ---------------------------------------------------------
            # THE SECRET: Update the "until" parameter for the next loop!
            # We request tweets strictly BEFORE the oldest one we just found.
            # ---------------------------------------------------------
            if oldest_timestamp:
                current_until = f"until_time:{oldest_timestamp}"

            # CHECKPOINTING
            file.flush()
            print(f"  Progress: {tweet_count}/{limit}")
            await asyncio.sleep(random.uniform(4, 7)) # Slightly larger pause for safety

        except NotFound:
            print(f"  End of results. Stopped at {tweet_count}.")
            break
        except TooManyRequests:
            print(f"  Excess of API request limits. Pause for 15 minutes and restart...")
            await asyncio.sleep(900)
            continue
        except Exception as e:
            print(f"  Unexpected Error: {e}")
            break

    print(f"  Completed: {tweet_count} tweets from: {since} to: {until}")
    return tweet_count

# EXECUTION
async def main():
    client = Client('en-US')

    print("Loading cookies...")
    try:
        client.set_cookies({'auth_token': AUTH_TOKEN, 'ct0': CT0})
        print("Cookies loaded!")

    except Exception as e:
        print(f"Problem with cookies: {e}")
        return

    total = 0

    file_exists = os.path.isfile(OUTPUT_FILE)

    with open(OUTPUT_FILE, 'a', newline='', encoding='utf-8-sig') as file:
        writer = csv.writer(file)

        if not file_exists:
          writer.writerow(['Date', 'Tweet_ID', 'Raw Text', 'Likes', 'Retweets', 'is_fire', 'is_wildland', 'is_urban'])
          file.flush()

        for since, until, limit, description in PERIODS:
            count = await scrape_period(client, since, until, limit, description, writer, file)
            total += count
            print(f"Pause for 10 seconds before scraping next period...") #small pause between sessions
            await asyncio.sleep(10)

    print(f"\nScraping completed! A total of {total} tweets were saved to: {OUTPUT_FILE}")

await main()