# -*- coding: utf-8 -*-
"""Part3_Binary_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWy0ChWlYuaOpvrAluemvch_P-OQOpqN

# Model Training & Evaluation Script (Binary Classification)

**Description**

This script implements the binary classification of
Greek Twitter (X) posts (Fire vs. Non-Fire related) extracted from a preprocessed (cleaned and manually labeled) dataset.

Models investigated:


1.   **Baseline SVM**

*   TF-IDF Vectorization
*   Standard model used mainly for comparison reasons


2.   **Advanced SVM**


*   TF-IDF Vectorization
*   5-Fold Cross Validation
*   Grid Search (for automated hyperparameter tuning)

3.   **GreekBERT**


*   Greek version of Google's BERT (Mono-lingual)
*   Fine-tuning
*   Error Analysis (focused on False Negatives for minimization of missed fire events)


4.   **XLM-RoBERTa**


*   Multi-lingual model pre-trained from FacebookAI
*   Fine Tuning
*   Error Analysis (focused on False Negatives for minimization of missed fire events)



**References:**

*GreekBERT: https://github.com/nlpaueb/greek-bert*

*XLM-RoBERTa: https://huggingface.co/FacebookAI/xlm-roberta-base*
"""

# LIBRARIES
!pip install huggingface_hub -q

import pandas as pd
import numpy as np
import io
import torch
import matplotlib.pyplot as plt
from google.colab import files, userdata
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, precision_recall_fscore_support, fbeta_score, confusion_matrix, make_scorer
from sklearn.pipeline import Pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
from huggingface_hub import notebook_login, login

# 1. DATASΕΤ LOADING

print("You need to have the labeled and cleaned dataset already downloaded in your PC (CSV or Excel file).")
print("Please upload master_cleaned_dataset file here:")

# Upload the cleaned and labeled dataset
uploaded = files.upload()
filename = list(uploaded.keys())[0]
print(f"\nProcessing file: {filename}...")

# Load the file into a Pandas DataFrame based on its extension
if filename.endswith('.csv'):
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
elif filename.endswith(('.xls', '.xlsx')):
    df = pd.read_excel(io.BytesIO(uploaded[filename]))
else:
    raise ValueError("Unsupported file format. Please upload a .csv or .xlsx file.")

print(f"Dataset loaded successfully! Total dataset rows: {len(df)}\n")

# --- DATA SHUFFLE ---
# frac=1 means that we take 100% of the lines, but with random order.
# random_state=42 reassures that the shuffling will be the same every time we run the script.
# reset_index creates the numbering (0, 1, 2...) again, so that no gaps exist.
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Dataset was suffled successfully!")
df.to_excel("shuffled_dataset_check.xlsx", index=False) # We save the shuffled dataset for manual inspection
print("Shuffled dataset was saved on the Colab files.")

# 2. GLOBAL FUNCTIONS AND SETTINGS

# Lock randomness
from transformers import set_seed
set_seed(42)

# Custom Metrics with F2-Score Function
""" Calculates evaluation metrics (Precision, Recall, F1, F2) during training """
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
    f2 = fbeta_score(labels, predictions, beta=2.0, average='binary')

    return {
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'f2': f2
    }

# Evaluation Report Function
""" Αutomates the generation of the Confusion Matrix and Classification Report for each model """
def print_evaluation_report(y_true, y_pred, model_name):
    print(f"\n==================================================")
    print(f" Model Evaluation: {model_name}")
    print(f"==================================================")

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    cm_df = pd.DataFrame(cm,
                         index=['Actual: Non-Fire (0)', 'Actual: Fire (1)'],
                         columns=['Predicted: Non-Fire (0)', 'Predicted: Fire (1)'])
    print("\nConfusion Matrix:")
    print(cm_df)

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred))

    # Metrics
    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='binary')
    f2 = fbeta_score(y_true, y_pred, beta=2.0, average='binary')

    print(f"\nMetrics for {model_name}:")
    print(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1: {f1:.4f} | F2: {f2:.4f}")

def plot_training_history(trainer, model_name):
    """
    Extracts and plots the Loss (Training vs Validation) curves
    from the history of a Hugging Face Trainer.
    """
    print(f"\n--- Extracting model Loss Curves: {model_name} ---")

    history = trainer.state.log_history

    # Lists for data keeping
    train_loss = []
    eval_loss = []
    epochs = []

    # Search history to collect metrics for each epoch
    for entry in history:
        # If the record concerns Validation (has eval_loss)
        if 'eval_loss' in entry:
            eval_loss.append(entry['eval_loss'])
            epochs.append(entry['epoch'])
        # If the record concerns Training (has a loss)
        elif 'loss' in entry:
            train_loss.append(entry['loss'])

    # Check if there are enough data for the graph
    if not train_loss or not eval_loss:
        print("[ERROR]: Not enough loss data found in Trainer history.")
        return

    # Synchronization of list lengths (in case logs differ)
    min_length = min(len(train_loss), len(eval_loss))
    train_loss = train_loss[:min_length]
    eval_loss = eval_loss[:min_length]
    epochs = epochs[:min_length]

    # Graph Design
    plt.figure(figsize=(10, 6))
    plt.plot(epochs, train_loss, label='Training Loss', color='blue', marker='o', linewidth=2)
    plt.plot(epochs, eval_loss, label='Validation Loss', color='red', marker='x', linewidth=2)

    plt.title(f'Training vs Validation Loss - {model_name}', fontsize=14)
    plt.xlabel('Epochs', fontsize=12)
    plt.ylabel('Loss (Σφάλμα)', fontsize=12)
    plt.legend(fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)

    plt.show()

def perform_error_analysis(texts, y_true, y_pred, model_name):
    """
    Model Error Analysis Function:
    Identifies & categorizes misclassifications to an Excel file (with a primary focus on False Negatives),
    enabling an in-depth analysis of the errors occured
    """
    print(f"\n--- Starting {model_name} Error Analysis ---")

    # DataFrame Creation
    analysis_df = pd.DataFrame({
        f'Text Input': texts,
        'True Label': y_true,
        f'Prediction': y_pred
    })

    # We keep ONLY the errors (True Label vs Prediction)
    errors_df = analysis_df[analysis_df['True Label'] != analysis_df['Prediction']].copy()

    # Error Categorization
    # We pay special attention to False Negatives (Missed Fires)
    def categorize_error(row):
        if row['True Label'] == 0 and row['Prediction'] == 1:
            return 'False Positive (False Alarm)'
        elif row['True Label'] == 1 and row['Prediction'] == 0:
            return 'False Negative (Missed Fire)'
        return 'Unknown'

    errors_df['Error Type'] = errors_df.apply(categorize_error, axis=1)
    errors_df = errors_df.sort_values(by='Error Type')

    # Print False Negatives
    false_negatives = errors_df[errors_df['Error Type'] == 'False Negative (Missed Fire)']

    print(f"\n" + "="*70)
    print(f"Caution: {len(false_negatives)} False Negatives (Missed Fires) Found in {model_name}")
    print("="*70)

    for index, row in false_negatives.iterrows():
        print(f"-> {row['Text Input']}\n")

    print("="*70)

    # File Save and Download
    safe_model_name = model_name.replace('-', '_').replace(' ', '_')
    output_filename = f"{safe_model_name}_Error_Analysis.xlsx"

    errors_df.to_excel(output_filename, index=False)

    print(f"\nAnalysis complete! Found a total of {len(errors_df)} misclassified tweets.")
    print(f"You can download {output_filename} from the Colab's File section...")

# 3a. BASELINE MODEL: SVM with TF-IDF

print("\n--- Training Model: SVM with TF-IDF ---")

# We use the 'Hard Cleaned Text' fo r traditional ML models like SVM
X_svm = df['Hard Cleaned Text'].values
y_svm = df['is_fire'].values

# 1st Split: 70% Train and 30% temporal
X_train_svm, X_temp_svm, y_train_svm, y_temp_svm = train_test_split(
    X_svm, y_svm, test_size=0.30, random_state=42, stratify=y_svm
)

# 2nd Split: Cut temporal 30% in half -> 15% Val, 15% Test
X_val_svm, X_test_svm, y_val_svm, y_test_svm = train_test_split(
    X_temp_svm, y_temp_svm, test_size=0.50, random_state=42, stratify=y_temp_svm
)
# Note: When training SVM the Validation set (X_val_svm, y_val_svm) is being ignored,
# because the evaluation is executed through K-Fold CV in the Training set.
# ------------------------------------------------------------------

# TF-IDF Vectorization
# max_features keeps the most common vocabulary (e.g. 5000 words) to avoid memory issues and overfitting
tfidf_vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_svm)
X_test_tfidf = tfidf_vectorizer.transform(X_test_svm)

# Initialize and Train SVM
# Using class_weight='balanced' is crucial for highly imbalanced datasets
svm_model = SVC(kernel='linear', class_weight='balanced', random_state=42)
svm_model.fit(X_train_tfidf, y_train_svm)

# Model Prediction
y_pred_simple = svm_model.predict(X_test_tfidf)

# Model Evaluation (Simple SVM)
print_evaluation_report(y_test_svm, y_pred_simple, "Simple SVM (Baseline)")

print("\nSimple SVM execution complete!")

# 3b. SVM with TF-IDF & 5-Fold Cross Validation (Grid Search)
# We test Cross Validation (K-Fold) and Grid Search (hyperparameter tuning) for better results

print("\n--- Training model: SVM with K-Fold & Grid Search ---")

# We use the 'Hard Cleaned Text' for traditional ML models like SVM
X_svm = df['Hard Cleaned Text'].values
y_svm = df['is_fire'].values

# 1st Split: 70% for Training and 30% temporal
X_train_svm, X_temp_svm, y_train_svm, y_temp_svm = train_test_split(
    X_svm, y_svm, test_size=0.30, random_state=42, stratify=y_svm
)

# 2nd Split: Cut 30% in half -> 15% Val, 15% Test
X_val_svm, X_test_svm, y_val_svm, y_test_svm = train_test_split(
    X_temp_svm, y_temp_svm, test_size=0.50, random_state=42, stratify=y_temp_svm
)

# Pipeline
# During the K-Fold CV, the TF-IDF vocabulary should be built on the training (K-1) folds.
# That way data leakage from the (K) validation fold is prevented.
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
    ('svm', SVC(kernel='linear', class_weight='balanced', random_state=42))
])

# Parameter selection for Grid Search

# max_features is the total size of the vocabulary selected
# We test: 5000, 10000
# C controls the trade-off between a wider margin (low C) and correctly classifying all points (high C).
# We test: 0.1, 1, 5, 10, 50
# Total of 2x5=10 models to be tested. Each one 5 times (5-Fold)

param_grid = {
    'tfidf__max_features': [5000, 10000],
    'svm__C': [0.1, 1, 5, 10, 50]
}

# Grid Search
# fbeta_score calculates custom F_scores (we want F2-score which is beta=2.0)
f2_scorer = make_scorer(fbeta_score, beta=2.0)

# We select to search for the best F2-score by using a 5-fold CV
# n_jobs=-1 utilizes all available CPU cores
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring=f2_scorer, n_jobs=-1, verbose=1)

print("Starting Grid Search...")
print("Optimization based on F2-Score...")
grid_search.fit(X_train_svm, y_train_svm)

# Winner model
print(f"\nBest hypermeter selection:")
print(grid_search.best_params_)

# Model Prediction based on the locked Test Set (20%)
# grid_search uses the winner model for the prediction
y_pred_best = grid_search.predict(X_test_svm)

# Model Evaluation (Advanced SVM)
print_evaluation_report(y_test_svm, y_pred_best, "Advanced SVM (K-Fold & GridSearch)")

print("\nSVM with K-Fold & Grid Search execution complete!")

# 4a. Training Model: GreekBERT

print("\n--- Training Model: GreekBERT ---")

# Definition of the pre-trained GreekBERT model
model_name = "nlpaueb/bert-base-greek-uncased-v1"

# Load Tokenizer
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)

# We use the 'Advanced Cleaned Text' for uncased Transformer models
X_bert = df['Advanced Cleaned Text'].tolist()
y_bert = df['is_fire'].tolist()

# 1st Split: Keep 30% for Val & Test - Train is assigned 70%.
X_train_b, X_temp, y_train_b, y_temp = train_test_split(
    X_bert, y_bert, test_size=0.30, random_state=42, stratify=y_bert
)

# 2nd Split: Cut X_temp in half to take 15% Val και 15% Test
X_val_b, X_test_b, y_val_b, y_test_b = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

# Tokenization function
def tokenize_function(examples):
    return tokenizer_bert(examples['text'], padding="max_length", truncation=True, max_length=128)

train_dataset = Dataset.from_dict({'text': X_train_b, 'label': y_train_b})
val_dataset = Dataset.from_dict({'text': X_val_b, 'label': y_val_b})
test_dataset = Dataset.from_dict({'text': X_test_b, 'label': y_test_b})

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Load Model for Sequence Classification (Binary: num_labels=2)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# Definition of Training Arguments
# Hyperparameter Tuning: Epochs, batch size, and learning rate can be tuned for better results
training_args = TrainingArguments(
    output_dir='./results',
    hub_model_id="mariossmrs/greek-bert-fire-detection-binary-classification",
    num_train_epochs=4, # Tuning
    per_device_train_batch_size=16, # Tuning
    per_device_eval_batch_size=32, # Tuning
    learning_rate=5e-6, # Tuning
    weight_decay=0.1, # Tuning - INCREASE: Greater penalty for memorization
    warmup_ratio=0.1, # Tuning - The first 10% of steps are a gradual "warm-up"
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f2",      # Uses "F2-Score" to optimize the training
    greater_is_better=True,          # Greater F2-Score is better
    fp16=True,                      #  GPU acceleration - turn to True when training the big dataset
    report_to="none",
    logging_dir='./logs',
    logging_strategy="epoch" # for 'no log' error
)

# Initialize Trainer
trainer_bert = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# Model Training
print("Starting BERT fine-tuning...")
trainer_bert.train()

# Predictions Extraction
raw_predictions, _, _ = trainer_bert.predict(test_dataset)
y_pred_bert = np.argmax(raw_predictions, axis=1)

# Evaluation Report
print_evaluation_report(y_test_b, y_pred_bert, "GreekBERT")

# Loss Curve
#plot_training_history(trainer_bert, "GreekBERT")

# 4b. GreekBERT ERROR ANALYSIS
perform_error_analysis(X_test_b, y_test_b, y_pred_bert, "GreekBERT")

# 5a. Training Model: XLM-RoBERTa

print("\n--- Training Model: XLM-RoBERTa ---")

# Definition of of the pre-trained XLM-RoBERTa model
model_name_xlm = "xlm-roberta-base"
tokenizer_xlm = AutoTokenizer.from_pretrained(model_name_xlm)

# We use the 'Light Cleaned Text' because RoBERTa corresponds to casing and diacritics
X_xlm = df['Light Cleaned Text'].astype(str).tolist()
y_xlm = df['is_fire'].tolist()

# 1st Split: 30% for Val & Test
X_train_x, X_temp_x, y_train_x, y_temp_x = train_test_split(
    X_xlm, y_xlm, test_size=0.30, random_state=42, stratify=y_xlm
)

# 2nd Split: Τhe temporal 30% is cut in half -> 15% Val, 15% Test
X_val_x, X_test_x, y_val_x, y_test_x = train_test_split(
    X_temp_x, y_temp_x, test_size=0.50, random_state=42, stratify=y_temp_x
)

def tokenize_xlm(examples):
    return tokenizer_xlm(examples['text'], padding="max_length", truncation=True, max_length=128)

train_ds_xlm = Dataset.from_dict({'text': X_train_x, 'label': y_train_x}).map(tokenize_xlm, batched=True)
val_ds_xlm = Dataset.from_dict({'text': X_val_x, 'label': y_val_x}).map(tokenize_xlm, batched=True)
test_ds_xlm = Dataset.from_dict({'text': X_test_x, 'label': y_test_x}).map(tokenize_xlm, batched=True)

model_xlm = AutoModelForSequenceClassification.from_pretrained(model_name_xlm, num_labels=2)

# Definition of Training Arguments
# Hyperparameter Tuning: Epochs, batch size, and learning rate can be tuned for better results
training_args_xlm = TrainingArguments(
    output_dir='./results_xlm',
    num_train_epochs=4, # Tuning
    per_device_train_batch_size=16, # Tuning
    learning_rate=5e-6, # Tuning
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f2",
    weight_decay=0.1,          # Tuning
    warmup_ratio=0.1,          # Tuning
    fp16=True,
    report_to="none",
    logging_strategy="epoch" #test for 'no log'
)

trainer_xlm = Trainer(
    model=model_xlm,
    args=training_args_xlm,
    train_dataset=train_ds_xlm,
    eval_dataset=val_ds_xlm,
    compute_metrics=compute_metrics
)

# Model Training
print("Starting RoBERTa fine-tuning...")
trainer_xlm.train()

# Predictions Extraction
raw_preds_xlm, _, _ = trainer_xlm.predict(test_ds_xlm)
y_pred_xlm = np.argmax(raw_preds_xlm, axis=1)

# Model Evaluation
print_evaluation_report(y_test_x, y_pred_xlm, "XLM-RoBERTa")

# Loss Curves
#plot_training_history(trainer_xlm, "XLM-RoBERTa")

print("\nXLM-RoBERTa execution complete!")

# 5b. ERROR ANALYSIS: XLM-RoBERTa
perform_error_analysis(X_test_x, y_test_x, y_pred_xlm, "XLM-RoBERTa")

# ==========================================
# Model Upload to HUGGING FACE
# ==========================================
from google.colab import userdata
from huggingface_hub import login
# SOS: Switch to 'True' ONLY for model upload to Hugging Face. For local run/model evaluation switch to 'False'
UPLOAD_TO_HUB = False

if UPLOAD_TO_HUB:
    print("Prepairing upload to Hugging Face...")

    # Login credential / token authorization
    hf_token = userdata.get('HF_TOKEN')
    login(token=hf_token)

    repo_name = "mariossmrs/greek-bert-fire-detection-binary-classification" # Comment depending on the model to be saved (GreekBERT or XLM-RoBERTa)
    #repo_name = "mariossmrs/greek-xlm-roberta-fire-detection-binary-classification" # Comment depending on the model to be saved (GreekBERT or XLM-RoBERTa)

    print("Uploading in progress...")
    trainer_bert.push_to_hub(repo_name) # trainer_bert or trainer_xlm depending on the best model
    tokenizer_bert.push_to_hub(repo_name) # tokenizer_bert or tokenizer_xlm depending on the best model
    print("Model was saved succefully!")

else:
    print("The option to upload to Hugging Face is disabled. (UPLOAD_TO_HUB = False).")
    print("The model remains stored only locally in Colab.")