# -*- coding: utf-8 -*-
"""Part4_Multilabel_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYoH12Hv6bzRWlIsfPRuARdf8HqGU2w9

# Model Training & Evaluation Script (Multi-label Classification)

**Description**

This script implements the multi-label classification of Greek Twitter (X) posts.
It specifically targets ONLY the posts that have been already classified as Fire-related (Label = 1)
and attempts to identify the specific type of the fire by predicting two independent probabilities:
- is_wildland (Wildfire / Rural area)
- is_urban (Vehicles / Industrial / Infrastructure / Residential)

If both labels are predicted as 1, the event is classified as WUI (Wildland-Urban Interface) / Mixed.

Models investigated:
1. Baseline SVM (MultiOutputClassifier)
2. Advanced SVM (Grid Search & K-Fold CV)
3. GreekBERT (Fine-tuning for multi-label)
4. XLM-RoBERTa (Fine-tuning for multi-label)
"""

# LIBRARIES
!pip install huggingface_hub -q
!pip install seaborn -q








import pandas as pd
import numpy as np
import io
import torch
import matplotlib.pyplot as plt
import gc
import shutil
import os
import seaborn as sns
from google.colab import files, userdata
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import classification_report, precision_recall_fscore_support, fbeta_score, accuracy_score, make_scorer, multilabel_confusion_matrix, confusion_matrix, f1_score
from sklearn.pipeline import Pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, set_seed, EarlyStoppingCallback
from datasets import Dataset
from huggingface_hub import notebook_login, login
from torch import nn

# Lock randomness
set_seed(789)

# ==========================================
# 1. DATASΕΤ LOADING & PREPARATION (for manual)
# ==========================================
"""
print("You need to have the manually labeled and cleaned dataset already downloaded in your PC.")
print("Ensure you have added the 'is_wildland' and 'is_urban' columns for is_fire=1 tweets.\n")
print("Please upload master_cleaned_dataset file here:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
print(f"\nProcessing file: {filename}...")

if filename.endswith('.csv'):
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
elif filename.endswith(('.xls', '.xlsx')):
    df = pd.read_excel(io.BytesIO(uploaded[filename]))
"""
# ==========================================
# 1. DATASΕΤ LOADING & PREPARATION (for automated)
# ==========================================

print("Downloading 'master_cleaned_dataset.xlsx' directly from GitHub...")

# Github file URL
github_url = "https://github.com/mariossmrs/greek-wildfire-detection-pipeline/raw/refs/heads/main/data/master_cleaned_dataset.xlsx"

try:
    df = pd.read_excel(github_url)
    print("Dataset loaded successfully from GitHub!\n")
except Exception as e:
    print(f"Error loading dataset from GitHub: {e}")
    print("Please check the URL or your internet connection.")

# DATA FILTERING & FLOAT CONVERSION
# We only train the multi-label models on ACTUAL fire events. The other are discarded automatically.
df_fire = df[df['is_fire'] == 1].copy()

# GLOBAL DATA SHUFFLE
df_fire = df_fire.sample(frac=1, random_state=789).reset_index(drop=True)
print("Dataset was suffled successfully!")
df_fire.to_excel("shuffled_dataset_check.xlsx", index=False) # We save the shuffled dataset for manual inspection
print("Shuffled dataset was saved on the Colab files.\n")

# Fill empty cells (NaN) with 0 for the tweets that might have been skipped
df_fire['is_wildland'] = df_fire['is_wildland'].fillna(0)
df_fire['is_urban'] = df_fire['is_urban'].fillna(0)

# Convert to Float! (Crucial requirement for Hugging Face BCEWithLogitsLoss)
df_fire['is_wildland'] = df_fire['is_wildland'].astype(float)
df_fire['is_urban'] = df_fire['is_urban'].astype(float)

# Drop rows where text might be empty
df_fire = df_fire.dropna(subset=['Hard Cleaned Text', 'Advanced Cleaned Text'])

print(f"Original dataset size: {len(df)}")
print(f"Fire-only dataset size (used for training): {len(df_fire)}")

# ==========================================
# 2. GLOBAL FUNCTIONS AND SETTINGS
# ==========================================

def compute_metrics_multilabel(eval_pred):
    """ Calculates evaluation metrics for Combinational (4-State) Multi-label classification """
    logits, labels = eval_pred

    # 1. Apply Sigmoid to convert logits to independent probabilities (0 to 1)
    probs = torch.sigmoid(torch.Tensor(logits)).numpy()

    # 2. Apply Threshold (0.5) to get binary predictions
    predictions = (probs > 0.5).astype(int)

    labels = np.array(labels).astype(int)

    # 3. Exact Match Ratio (Subset Accuracy)
    exact_match = accuracy_score(labels, predictions)

    # 4. Convert [0,0], [0,1], [1,0], [1,1] to 4 classes (0, 1, 2, 3)
    # Logic: is_wildland * 2 + is_urban
    labels_4c = labels[:, 0] * 2 + labels[:, 1]
    preds_4c = predictions[:, 0] * 2 + predictions[:, 1]

    # 5. Calculation of Macro Metrics on the 4 classes combinatorial
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels_4c, preds_4c, average='macro', zero_division=0
    )

    return {
        'exact_match_ratio': exact_match,
        'macro_precision': precision, # 4-state macro
        'macro_recall': recall,       # 4-state macro
        'macro_f1': f1                # 4-state macro
    }

def print_multilabel_evaluation_report(y_true, y_pred, model_name):
    """ Prints a detailed 4-State Combinational report and plots a 4x4 Confusion Matrix """
    print(f"\n==================================================")
    print(f" Model Evaluation: {model_name} (Combinational 4-Class)")
    print(f"==================================================")

    y_true_np = np.array(y_true)
    y_pred_np = np.array(y_pred)

    # 1. Exact Match Ratio
    exact_match = accuracy_score(y_true_np, y_pred_np)
    print(f"Exact Match Ratio (Perfect Combinations): {exact_match:.4f}\n")

    # 2. Κωδικοποίηση στις 4 Καταστάσεις
    y_true_4c = y_true_np[:, 0] * 2 + y_true_np[:, 1]
    y_pred_4c = y_pred_np[:, 0] * 2 + y_pred_np[:, 1]

    target_names = [
        'Unidentified (0,0)',
        'Urban Only (0,1)',
        'Wildland Only (1,0)',
        'Mixed Fire (1,1)'
    ]

    # 3. Classification Report
    print("Classification Report (4-State Combinational):")
    print(classification_report(y_true_4c, y_pred_4c, target_names=target_names, zero_division=0, digits=4))

    # 4. 4x4 Confusion Matrix
    cm = confusion_matrix(y_true_4c, y_pred_4c, labels=[0, 1, 2, 3])

    plt.figure(figsize=(7, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=target_names, yticklabels=target_names)
    plt.xlabel('Predicted Target')
    plt.ylabel('True Target')
    plt.title(f'4x4 Combinational Confusion Matrix: {model_name}')

    plt.show()

def plot_training_history(trainer, model_name):
    """
    Plots the Training and Validation Loss curves from a Hugging Face Trainer.
    Extracts the exact epoch for each log to perfectly align the X-axis.
    """
    print(f"\nGenerating Loss Curves for {model_name}...")

    # Extract history from the Trainer
    history = trainer.state.log_history

    # Separate epochs and losses for training and validation
    train_epochs = [x['epoch'] for x in history if 'loss' in x]
    train_loss = [x['loss'] for x in history if 'loss' in x]

    eval_epochs = [x['epoch'] for x in history if 'eval_loss' in x]
    eval_loss = [x['eval_loss'] for x in history if 'eval_loss' in x]

    # Create the Plot
    plt.figure(figsize=(8, 5))

    if train_loss:
        plt.plot(train_epochs, train_loss, label='Training Loss', color='blue', marker='x')
    else:
        print(f"  [!] Warning: No training loss found for {model_name}. Did you set logging_strategy='epoch'?")

    if eval_loss:
        plt.plot(eval_epochs, eval_loss, label='Validation Loss', color='red', marker='o')

    plt.title(f'Training vs Validation Loss ({model_name})')
    plt.xlabel('Epochs')
    plt.ylabel('Loss (BCEWithLogitsLoss)')
    plt.legend()
    plt.grid(True)
    plt.show()

def optimize_thresholds(y_val_true, val_probs):
    """
    It tests combinations of thresholds for is_wildland and is_urban
    in order to maximize the 4-State Macro F1 in the Validation Set.
    """
    print("Optimization thresholds in progress...")

    best_t_wild = 0.5
    best_t_urban = 0.5
    best_macro_f1 = 0.0

    y_val_true_np = np.array(y_val_true).astype(int)
    # Coding of the actual labels (0, 1, 2, 3)
    y_val_4c = y_val_true_np[:, 0] * 2 + y_val_true_np[:, 1]

    # Testing thresholds from 0.10 to 0.90 with step 0.05
    threshold_range = np.arange(0.10, 0.95, 0.05)

    for t_wild in threshold_range:
        for t_urban in threshold_range:
            # Prediction based on current thresholds
            preds = np.zeros_like(val_probs)
            preds[:, 0] = (val_probs[:, 0] > t_wild).astype(int)
            preds[:, 1] = (val_probs[:, 1] > t_urban).astype(int)

            # 4 states
            preds_4c = preds[:, 0] * 2 + preds[:, 1]

            # Calculation of Macro F1
            current_f1 = f1_score(y_val_4c, preds_4c, average='macro', zero_division=0)

            # Save if it is better than the other ones
            if current_f1 > best_macro_f1:
                best_macro_f1 = current_f1
                best_t_wild = t_wild
                best_t_urban = t_urban

    print(f"Optimal Thresholds Found -> Wildland: {best_t_wild:.2f} | Urban: {best_t_urban:.2f}")
    print(f"Validation 4-State Macro F1 with optimal thresholds: {best_macro_f1:.4f}")

    return best_t_wild, best_t_urban

class CustomMultilabelTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # 1. We remove the actual labels from the input dictionary
        labels = inputs.pop("labels")

        # 2. We get the predictions (logits) from the model
        outputs = model(**inputs)
        logits = outputs.logits

        # 3. We define the weights [weight_is_wildland, weight_is_urban]
        # The numbers are derived from: (Total Negatives) / (Total Positives)
        pos_weights = torch.tensor([2.45, 1.32]).to(model.device)

        # 4. We implement BCEWithLogitsLoss with our own weights
        loss_fct = nn.BCEWithLogitsLoss(pos_weight=pos_weights)
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

# ==========================================
# 3a. BASELINE MODEL: SVM with TF-IDF (Multi-label)
# ==========================================
print("\n--- Training Model: Baseline SVM (Multi-label) ---")

X_svm = df_fire['Hard Cleaned Text'].values
# y is now a 2D array: [[is_wildland1, is_urban1], [is_wildland2, is_urban2], ...]
y_svm = df_fire[['is_wildland', 'is_urban']].values

# --- STRATIFIED SPLIT (70% Train, 15% Val, 15% Test) ---
# 4-State variable to guide stratify
y_stratify_svm = (y_svm[:, 0] * 2 + y_svm[:, 1]).astype(int)

X_train_svm, X_temp_svm, y_train_svm, y_temp_svm, y_strat_train_svm, y_strat_temp_svm = train_test_split(
    X_svm, y_svm, y_stratify_svm, test_size=0.30, random_state=789, stratify=y_stratify_svm
)

X_val_svm, X_test_svm, y_val_svm, y_test_svm = train_test_split(
    X_temp_svm, y_temp_svm, test_size=0.50, random_state=789, stratify=y_strat_temp_svm
)

tfidf_vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_svm)
X_test_tfidf = tfidf_vectorizer.transform(X_test_svm)

# MultiOutputClassifier wraps the SVC so it can handle 2 target columns simultaneously
base_svm = SVC(kernel='linear', probability=True, random_state=789) # Discarded class_weight='balanced'
svm_model = MultiOutputClassifier(base_svm)

svm_model.fit(X_train_tfidf, y_train_svm)
y_pred_simple = svm_model.predict(X_test_tfidf)

print_multilabel_evaluation_report(y_test_svm, y_pred_simple, "Simple SVM (Baseline)")

# ==========================================
# 3b. Advanced SVM: K-Fold & Grid Search
# ==========================================
print("\n--- Training model: Advanced SVM (K-Fold & Grid Search) ---")

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
    ('svm', MultiOutputClassifier(SVC(kernel='linear', class_weight='balanced', probability=True, random_state=789)))
])

# Note the syntax 'svm__estimator__C'. Because SVC is inside MultiOutputClassifier (which is inside the Pipeline),
# we must use 'estimator' to access the inner SVC parameters.

param_grid = {
    'tfidf__max_features': [3000, 5000],
    'tfidf__ngram_range': [(1, 1), (1, 2)],
    'svm__estimator__C': [0.1, 1, 5, 10],
}

# Custom scorer for GridSearch: Εφαρμόζουμε τον 4-State μετασχηματισμό
def combinational_macro_f1(y_true, y_pred):
    y_true_np = np.array(y_true)
    y_pred_np = np.array(y_pred)
    y_true_4c = y_true_np[:, 0] * 2 + y_true_np[:, 1]
    y_pred_4c = y_pred_np[:, 0] * 2 + y_pred_np[:, 1]
    return f1_score(y_true_4c, y_pred_4c, average='macro', zero_division=0)

combinational_scorer = make_scorer(combinational_macro_f1)

grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring=combinational_scorer, n_jobs=-1, verbose=1)

grid_search.fit(X_train_svm, y_train_svm)

print(f"\nBest hyperparameter selection:")
print(grid_search.best_params_)

y_pred_best = grid_search.predict(X_test_svm)
print_multilabel_evaluation_report(y_test_svm, y_pred_best, "Advanced SVM (GridSearch)")

# ==========================================
# 4. GreekBERT (Multi-label Fine-Tuning)
# ==========================================

# 1. Clean up memory from previous runs
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# 2. Manually overwrite/delete the old output directory
output_folder = './results_bert_multilabel' # (ή './results_bert_multilabel' στο κελί του GreekBERT)
if os.path.exists(output_folder):
    shutil.rmtree(output_folder)

print("\n[INFO] Memory and old checkpoints cleared. Ready for a fresh training run!")

print("\n--- Training Model: GreekBERT ---")

model_name_bert = "nlpaueb/bert-base-greek-uncased-v1"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name_bert)

X_bert = df_fire['Advanced Cleaned Text'].tolist()
y_bert = df_fire[['is_wildland', 'is_urban']].values.tolist() # Ensure it's a list of float lists

# --- STRATIFIED SPLIT (70-15-15) ---
y_bert_np = np.array(y_bert)
y_stratify_b = (y_bert_np[:, 0] * 2 + y_bert_np[:, 1]).astype(int)

X_train_b, X_temp_b, y_train_b, y_temp_b, y_strat_train_b, y_strat_temp_b = train_test_split(
    X_bert, y_bert, y_stratify_b, test_size=0.30, random_state=789, stratify=y_stratify_b
)

X_val_b, X_test_b, y_val_b, y_test_b = train_test_split(
    X_temp_b, y_temp_b, test_size=0.50, random_state=789, stratify=y_strat_temp_b
)

def tokenize_bert(examples):
    return tokenizer_bert(examples['text'], padding="max_length", truncation=True, max_length=128)

train_ds_bert = Dataset.from_dict({'text': X_train_b, 'label': y_train_b}).map(tokenize_bert, batched=True)
val_ds_bert = Dataset.from_dict({'text': X_val_b, 'label': y_val_b}).map(tokenize_bert, batched=True)
test_ds_bert = Dataset.from_dict({'text': X_test_b, 'label': y_test_b}).map(tokenize_bert, batched=True)

# The 'problem_type' argument automatically triggers BCEWithLogitsLoss for independent probabilities!
# BCEWithLogitsLoss uses Sigmoid instead of Softmax -> the probabilities for forest and urban are completely independent.
# E.g. If probs_xlm for a tweet outputs [0.85, 0.60], since both are above 0.5, the code will output [1, 1] (WUI)
model_bert = AutoModelForSequenceClassification.from_pretrained(
    model_name_bert,
    num_labels=2,
    problem_type="multi_label_classification"
)

training_args_bert = TrainingArguments(
    output_dir='./results_bert_multilabel',
    num_train_epochs=4, # Tuning
    per_device_train_batch_size=8, # Tuning
    learning_rate=2e-5, # Tuning
    eval_strategy="epoch",
    save_strategy="epoch",
    warmup_ratio=0.15, # Tuning
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1", # Optimize for Macro F1
    greater_is_better=True,
    fp16=True, # Set to True if using GPU for faster training
    report_to="none",
    logging_strategy="epoch", # To prevent from 'No log' in training loss
    weight_decay=0.1, # Tuning
    lr_scheduler_type="cosine"
)

trainer_bert = CustomMultilabelTrainer(
    model=model_bert,
    args=training_args_bert,
    train_dataset=train_ds_bert,
    eval_dataset=val_ds_bert,
    compute_metrics=compute_metrics_multilabel,
    # EarlyStopping will stop training if F1 does not increased in 2 consecutive epochs (patience=2) # Uncomment to test of early stopping
    #callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("Starting GreekBERT fine-tuning...")
trainer_bert.train()

print("\n--- 1. Validation & Threshold Optimization ---")
# Prediction on Validation Set (Important: To avoid data leakage)
raw_val_preds, _, _ = trainer_bert.predict(val_ds_bert)
val_probs = torch.sigmoid(torch.Tensor(raw_val_preds)).numpy()

# Find best thresholds
opt_t_wild, opt_t_urban = optimize_thresholds(y_val_b, val_probs)

print("\n--- 2. Final Evaluation on Test Set ---")
# Predictions on unseen Test Set
raw_test_preds, _, _ = trainer_bert.predict(test_ds_bert)
test_probs = torch.sigmoid(torch.Tensor(raw_test_preds)).numpy()

# Use best thresholds
y_pred_bert = np.zeros_like(test_probs)
y_pred_bert[:, 0] = (test_probs[:, 0] > opt_t_wild).astype(int)
y_pred_bert[:, 1] = (test_probs[:, 1] > opt_t_urban).astype(int)

# Final Evaluation Report
print_multilabel_evaluation_report(y_test_b, y_pred_bert, "GreekBERT (Optimized Thresholds)")
plot_training_history(trainer_bert, "GreekBERT")

# ==========================================
# 5. XLM-RoBERTa (Multi-label Fine-Tuning)
# ==========================================

# 1. Clean up memory from previous runs
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# 2. Manually overwrite/delete the old output directory
output_folder = './results_xlm_multilabel' # (ή './results_bert_multilabel' στο κελί του GreekBERT)
if os.path.exists(output_folder):
    shutil.rmtree(output_folder)

print("\n[INFO] Memory and old checkpoints cleared. Ready for a fresh training run!")
print("\n--- Training Model: XLM-RoBERTa ---")

model_name_xlm = "xlm-roberta-base"
tokenizer_xlm = AutoTokenizer.from_pretrained(model_name_xlm)

X_xlm = df_fire['Light Cleaned Text'].astype(str).tolist()
y_xlm = df_fire[['is_wildland', 'is_urban']].values.tolist()

# --- STRATIFIED SPLIT (70-15-15) ---
y_xlm_np = np.array(y_xlm)
y_stratify_x = (y_xlm_np[:, 0] * 2 + y_xlm_np[:, 1]).astype(int)

X_train_x, X_temp_x, y_train_x, y_temp_x, y_strat_train_x, y_strat_temp_x = train_test_split(
    X_xlm, y_xlm, y_stratify_x, test_size=0.30, random_state=789, stratify=y_stratify_x
)

X_val_x, X_test_x, y_val_x, y_test_x = train_test_split(
    X_temp_x, y_temp_x, test_size=0.50, random_state=789, stratify=y_strat_temp_x
)

def tokenize_xlm(examples):
    return tokenizer_xlm(examples['text'], padding="max_length", truncation=True, max_length=128)

train_ds_xlm = Dataset.from_dict({'text': X_train_x, 'label': y_train_x}).map(tokenize_xlm, batched=True)
val_ds_xlm = Dataset.from_dict({'text': X_val_x, 'label': y_val_x}).map(tokenize_xlm, batched=True)
test_ds_xlm = Dataset.from_dict({'text': X_test_x, 'label': y_test_x}).map(tokenize_xlm, batched=True)

model_xlm = AutoModelForSequenceClassification.from_pretrained(
    model_name_xlm,
    num_labels=2,
    problem_type="multi_label_classification"
)

training_args_xlm = TrainingArguments(
    output_dir='./results_xlm_multilabel',
    hub_model_id="mariossmrs/greek-xlm-roberta-fire-type-multilabel-classification",
    num_train_epochs=5,
    per_device_train_batch_size=8,
    learning_rate=3e-5,
    warmup_ratio=0.15,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1", # Selects the best training checkpoint based on the unweighted average F1 score across all labels.
    fp16=True, # Set to True if using GPU
    greater_is_better=True,
    report_to="none",
    logging_strategy="epoch", # To prevent from 'No log' in training loss
    weight_decay=0.1, # Tuning
    lr_scheduler_type="cosine"
)

trainer_xlm = CustomMultilabelTrainer(
    model=model_xlm,
    args=training_args_xlm,
    train_dataset=train_ds_xlm,
    eval_dataset=val_ds_xlm,
    compute_metrics=compute_metrics_multilabel,
    # EarlyStopping will stop training if F1 does not increased in 2 consecutive epochs (patience=2)
    #callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("Starting XLM-RoBERTa fine-tuning...")
trainer_xlm.train()

# Exact Match Ratio: Strict accuracy -> requires perfect prediction of the entire label combination [is_wildland, is_urban].
# Macro Precision: Accuracy of our positive predictions, averaged equally across both labels (minimizes false alarms).
# Macro Recall: The model's ability to identify all actual events, averaged equally (minimizes missed events).
# Macro F1: Harmonic mean of Precision and Recall, treating frequent and rare labels with equal importance.

print("\n--- 1. Validation & Threshold Optimization ---")
# Predictions on Validation Set (Important: to avoid data leakage)
raw_val_preds_xlm, _, _ = trainer_xlm.predict(val_ds_xlm)
val_probs_xlm = torch.sigmoid(torch.Tensor(raw_val_preds_xlm)).numpy()

# Find best thresholds for XLM-RoBERTa
opt_t_wild_xlm, opt_t_urban_xlm = optimize_thresholds(y_val_x, val_probs_xlm)

print("\n--- 2. Final Evaluation on Test Set ---")
# Predictions on unseen Test Set
raw_test_preds_xlm, _, _ = trainer_xlm.predict(test_ds_xlm)
test_probs_xlm = torch.sigmoid(torch.Tensor(raw_test_preds_xlm)).numpy()

# Best thresholds on Test Set
y_pred_xlm = np.zeros_like(test_probs_xlm)
y_pred_xlm[:, 0] = (test_probs_xlm[:, 0] > opt_t_wild_xlm).astype(int)
y_pred_xlm[:, 1] = (test_probs_xlm[:, 1] > opt_t_urban_xlm).astype(int)

# Final Evaluation Report
print_multilabel_evaluation_report(y_test_x, y_pred_xlm, "XLM-RoBERTa (Optimized Thresholds)")
plot_training_history(trainer_xlm, "XLM-RoBERTa")

print("\nPipeline Execution Complete!")

# ==========================================
# Model Upload to HUGGING FACE
# ==========================================
from google.colab import userdata
from huggingface_hub import login
# SOS: Switch to 'True' ONLY for model upload to Hugging Face. For local run/model evaluation switch to 'False'
UPLOAD_TO_HUB = False

if UPLOAD_TO_HUB:
    print("Prepairing upload to Hugging Face...")

    # Login credential / token authorization
    hf_token = userdata.get('HF_TOKEN')
    login(token=hf_token)

    #repo_name = "mariossmrs/greek-bert-fire-type-multilabel-classification" # Comment depending on the model to be saved (GreekBERT or XLM-RoBERTa)
    repo_name = "mariossmrs/greek-xlm-roberta-fire-type-multilabel-classification" # Comment depending on the model to be saved (GreekBERT or XLM-RoBERTa)

    print("Uploading in progress...")
    trainer_xlm.push_to_hub(repo_name) # trainer_bert or trainer_xlm depending on the best model
    tokenizer_xlm.push_to_hub(repo_name) # tokenizer_bert or tokenizer_xlm depending on the best model
    print("Model was saved succefully!")

else:
    print("The option to upload to Hugging Face is disabled. (UPLOAD_TO_HUB = False).")
    print("The model remains stored only locally in Colab.")